### DISCUSSION TITLE
Readonly Flag in openapi and validation

### DISCUSSION THREAD

**Discussion by ahoeing** [SDA-SE/sda-dropwizard-commons#1665] [Ideas]
Hello @SDA-SE/sda-commons-maintainer ,

we had a discussion some times ago about resource models with read/write models. @christopher-cudennec , you should remember at least ;)

We currently favour the usage of the readonly flag in openapi specifications for such attributes that cannot be set by consumers instead of creating read and write model
```yaml
          id:
            type: "string"
            description: "Technical identifier of the CommunicationAddress which will\
              \ be generated if not provided"
            readOnly: true
            example: "c0399bc8-81c9-11eb-8dcd-0242ac13000"
```

This flag can be created with openapi annotations in java:
```java
  @Schema(
      description =
          "Technical identifier of the partner which will be generated if not " + "provided",
      example = "fabe4baa-81c8-11eb-8dcd-0242ac130003",
      accessMode = Schema.AccessMode.READ_ONLY,
      required = true)
```

But this annotation does not cause a real validation, that the field is not set in writing operations.
Validation can be implemented with a custom validator
```java
public class ReadOnlyValidator implements ConstraintValidator<ReadOnly, Object> {
  @Override
  public boolean isValid(Object value, ConstraintValidatorContext context) {
    return value == null;
  }
}
```

and used e.g. that way
```java
  @ReadOnly(groups = CheckReadOnly.class)
  private String id;
```
with activation of this validation only for operations writing the resource
```java
  Response write(
          @NotNull
          @Valid
          @Validated(CheckReadOnly.class)
          Resource resource);
```

I think this feature can also be helpful for others and I would like to contribute that instead of creating my own library.

André
