### ISSUE TITLE
Endless loop when using sda-commons-server-kafka with Schema-Registry and getting a RecordDeserializationException

### ISSUE THREAD

**Issue by siom79** [SDA-SE/sda-dropwizard-commons#2149]
To use schema validation against a schema registry, one must configure a separate Deserializer in config.yml:
```yaml
    consumer-xxx:
      group: my-group
      config:
        value.deserializer: "io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer"
```
In case the Deserializer throws a `RuntimeException` (e.g. `RecordDeserializationException` in case of an invalid magic byte), the code in the `MessageListener`'s `run()`-method runs in an endless loop logging the same error again and again, flooding the logs without a possibility to skip the invalid record.

Please provide some means to inspect the exception and to skip the record or at least stop processing. You could for example add a method `processException()` to the `MessageListenerStrategy` that handles the exception and the strategies can dispatch these exceptions to the `MessageHandler`.
